---
title: "Simple document"
output: github_document
---



```{r}
library(tidyverse)
library(readr)
```


Let's import litters. ---csv


```{r}
litters_df = {
  read.csv("C:/2023Fall/DS2023/data_wrangling1/data_import_examples/FAS_litters.csv")
}

# I can also import the file from relative path.
# getwd()
# We'd better use relative path, because it will move with the project.

head(litters_df)

```

# Blanks

```{r}
litters_df = 
  janitor::clean_names(litters_df)

head(litters_df)
tail(litters_df)
str(litters_df)
```

Import Pups dataset

```{r}
pups_df = 
  read.csv("data_import_examples/FAS_pups.csv")

pups_df = 
  janitor::clean_names(pups_df)
```

Use the 'view' to get the entire dataset. Use the eval = False to mute the outcomes with function view.


# SKIM

```{r}
skimr::skim(pups_df)
```

# SKIP and SAVE the col_names(read_csv, needs the package readr)

```{r}
litters_df = 
   read_csv(
     "data_import_examples/FAS_litters.csv",
     skip = 10, col_names = FALSE
   )




```

# DATA TYPE

```{r}
litters_df = 
  read_csv(
    "data_import_examples/FAS_litters.csv",
    col_types = 
      cols(
        `GD0 weight` = col_character()
      ))


```

# IMPORT A SAS file

```{r}
library(haven)
pulse_df = 
  read_sas("data_import_examples/public_pulse_data.sas7bdat")
```



